import Head from 'next/head';
import Link from 'next/link';
import styles from '../../components/PageLayout/index.module.css';

export function PageLayout({ children, title = 'NewsApp' }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={styles.header}>
        <div>
          <Link href='/'>news</Link>
        </div>
        <div>
          <Link href='/about'>About</Link>
        </div>
      </header>
      <main>{children}</main>
    </>
  );
}
